### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ctrlaltvikas** [negomi/simple-build#1]
Hey @negomi . Are you still working on this?  Can you also include a demo link for this repo?

**Comment by negomi** [comment]
Hey @vikaskyadav, I haven't touched it for a long time to be honest :)

It's just a project starter so doesn't have any content or styles to demo (it just looks like a blank page to start with). Hope that helps!

**Comment by ctrlaltvikas** [comment]
Oh. Okay. I just thought that it was sort of like a package that just do environment setup for tedious tasks like that of react setup on local computer. Anyway. Thanks. :)
